steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker build -t $IMAGE .
    docker push $IMAGE
images:
- '$IMAGE'
options:
  machineType: 'E2_HIGHCPU_8'
