steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker build -f live-data-collector-service/Dockerfile -t $_IMAGE .
    docker push $_IMAGE

images:
- '$_IMAGE'

options:
  machineType: 'E2_HIGHCPU_8'
  substitutionOption: 'ALLOW_LOOSE'
  defaultLogsBucketBehavior: 'REGIONAL_USER_OWNED_BUCKET'

# Force builds to run in us-west2
location: 'us-west2'
