steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    cd go-services/wait-times-api
    docker build -t $_IMAGE .
    docker push $_IMAGE

images:
- '$_IMAGE'

options:
  machineType: 'E2_HIGHCPU_8'
  substitutionOption: 'ALLOW_LOOSE'
